version: '3.7'

services:
  pg:
    image: postgres:15-alpine
    container_name: saas-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
    volumes:
      - .data:/var/lib/postgresql/data